---
title: "ass4_mia"
output: html_document
date: "2023-05-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# packages

pacman::p_load(tidyverse, cmdstanr, brms, furrr, patchwork)

# load data 

df_raw = read.table('AlienData.txt',sep=',', header = T)

df <- df_raw %>% 
  filter(session == 2,
         condition == 2) %>% 
  mutate(response = ifelse(response == 3, 1, 
                           ifelse(response == 4, 1, 0)),
         correct = ifelse(response == dangerous, 1, 0))

df$stimulus = substr(df$stimulus, 1, nchar(df$stimulus)-4)

df$col1 <- as.numeric(substr(df$stimulus, 1, 1))
df$col2 <- as.numeric(substr(df$stimulus, 2, 2))
df$col3 <- as.numeric(substr(df$stimulus, 3, 3))
df$col4 <- as.numeric(substr(df$stimulus, 4, 4))
df$col5 <- as.numeric(substr(df$stimulus, 5, 5))

```

```{r}
# simulate features

eyes <- c(0,1)
spots <- c(0,1)
color <- c(0,1)
arms <- c(0,1)
legs <- c(0,1)

stimuli <- expand_grid(eyes, spots, color, arms, legs)

stimuli <- stimuli %>% 
  mutate(danger = ifelse(arms == 1, 1, 0),
         stimulus = row_number())

```

```{r}
sequence <- c()
for (i in 1:3) {
  temp <- sample(seq(32), 32, replace = F)
  sequence <- append(sequence, temp)
}

exp <- tibble(stimulus = sequence)

experiment <-  merge(stimuli, exp)

experiment <-  experiment[sample(1:nrow(experiment)), ]

```

```{r}
# Distance 
distance <- function(vect1, vect2, w) {
  return(sum(w * abs(vect1 - vect2)))
}

# Similarity
similarity <- function(distance, c) {
  return(exp(-c * distance))
}
```

```{r}
gcm <- function(w, c, obs, cat_one, quiet = TRUE) {
  # create an empty list to save probability of saying "1" for each trial
  r <- c()
  
  ntrials <- nrow(obs)
  
  for (i in 1:ntrials) {
    # If quiet is FALSE, print every ten trials
    if (!quiet && i %% 10 == 0) {
      print(paste("i =", i))
    }
    # if this is the first trial, or there any category with no exemplars seen yet, set the choice to random
    if (i == 1 || sum(cat_one[1:(i - 1)]) == 0 || sum(cat_one[1:(i - 1)]) == (i - 1)) {
      r <- c(r, .5)
    } else {
      similarities <- c()
      # for each previously seen stimulus assess distance and similarity
      for (e in 1:(i - 1)) {
        sim <- similarity(distance(obs[i, ], obs[e, ], w), c)
        similarities <- c(similarities, sim)
      }
      # Calculate prob of saying "1" by dividing similarity to 1 by the sum of similarity to 1 and to 2
      numerator <- sum(similarities[cat_one[1:(i - 1)] == 1])
      
      denominator <- sum(similarities[cat_one[1:(i - 1)] == 1]) + sum(similarities[cat_one[1:(i - 1)] == 0])
      
      r <- c(r, numerator / denominator)
    }
  }

  return(rbinom(ntrials, 1, r))
}
```


```{r}
# function for simulation responses
simulate_responses <- function(agent, w, c) {
    
    observations <- experiment %>%
        select(-c("stimulus", "danger"))
    
    category <- experiment$danger
    
    if (w == "equal") {
        weight <- rep(1 / 5, 5)
    } 
    else if (w == "optimal") {
         weight <- c(0, 0, 0, 1, 0)
     } 
    else if (w == "skewed") {
         weight <- c(0.5, 0.5, 0, 0, 0)
     }

    # simulate responses
    responses <- gcm(
        weight,
        c,
        observations,
        category
    )
    
    tmp_simulated_responses <- experiment %>%
        mutate(
            trial = seq(nrow(experiment)),
            sim_response = responses,
            correct = ifelse(category == sim_response, 1, 0),
            performance = cumsum(correct) / seq_along(correct),
            c = c,
            w = w,
            agent = agent
        )

    return(tmp_simulated_responses)
}


# simulate responses

param_df <- dplyr::tibble(
    expand_grid(
        agent = 1,
        c = seq(0.1, 2, 0.2),
        w = c("equal", "optimal", "skewed")
    )
)

simulated_responses <- future_pmap_dfr(param_df,
    simulate_responses,
    .options = furrr_options(seed = TRUE)
)

```

```{r}
p3 <- simulated_responses %>%
  mutate(w = as.factor(w)) %>%
  ggplot(aes(trial, performance, group = w, color = w)) +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
  theme_bw() +
  facet_wrap(c ~ .)

p4 <- simulated_responses %>%
  mutate(c = as.factor(c)) %>%
  ggplot(aes(trial, performance, group = c, color = c)) +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
  theme_bw() +
  facet_wrap(w ~ .)

p3 + p4
```

```{r}
file <- file.path("gcm.stan")
mod_GCM <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
```


```{r}
d = simulated_responses %>% 
  filter(c == '1.3',
         w == 'skewed')

gcm_data <- list(
  ntrials = nrow(d),
  nfeatures = 5,
  cat_one = d$danger,
  y = d$sim_response,
  obs = as.matrix(d[, c("eyes", "spots", "color", "arms", "legs")]),
  w_prior_values = c(1, 1, 1, 1, 1),
  c_prior_values = c(0, 1)
)

samples_gcm <- mod_GCM$sample(
  data = gcm_data,
  seed = 123,
  chains = 1,
  parallel_chains = 1,
  threads_per_chain = 4,
  iter_warmup = 1000,
  iter_sampling = 1000,
  refresh = 500
)

obs = as.matrix(d[, c("eyes", "spots", "color", "arms", "legs")])
```

```{r}
samples_gcm$summary()
```

```{r}
draws_df <- as_draws_df(samples_gcm$draws())

p1 <- ggplot(draws_df, aes(.iteration, c, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p2 <- ggplot(draws_df, aes(.iteration, logit_c, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
```

```{r}
p3 <- ggplot(draws_df, aes(.iteration, `w[1]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p4 <- ggplot(draws_df, aes(.iteration, `w[2]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p5 <- ggplot(draws_df, aes(.iteration, `w[3]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p6 <- ggplot(draws_df, aes(.iteration, `w[4]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p7 <- ggplot(draws_df, aes(.iteration, `w[5]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

(p1+p2)/(p3+p4+p5+p6+p7)
```
```{r}
pp1 <- ggplot(draws_df) +
  geom_density(aes(c), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(c_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = d$c[1]) +
  theme_bw()
```

```{r}
pp2 <- ggplot(draws_df) +
  geom_density(aes(`w[1]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[1]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 0) +
  theme_bw()

pp3 <- ggplot(draws_df) +
  geom_density(aes(`w[2]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[2]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 0) +
  theme_bw()

pp4 <- ggplot(draws_df) +
  geom_density(aes(`w[3]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[3]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 0) +
  theme_bw()

pp5 <- ggplot(draws_df) +
  geom_density(aes(`w[4]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[4]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 1) +
  theme_bw()

pp6 <- ggplot(draws_df) +
  geom_density(aes(`w[5]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[5]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 0) +
  theme_bw()

(pp1+pp2+pp3)/(pp4+pp5+pp6)
```

```{r}
draws_df %>% ggplot() +
  geom_density(aes(`r[10]`), fill = 'lightblue') +
  geom_density(aes(`r_prior[10]`), fill = 'pink')
```

```{r}
d <-  df %>% 
  filter(subject == 2) 
  

gcm_data <- list(
  ntrials = nrow(d),
  nfeatures = 5,
  cat_one = d$dangerous,
  y = d$response,
  obs = as.matrix(d[, c("col1", "col2", "col3", "col4", "col5")]),
  w_prior_values = c(1, 1, 1, 1, 1),
  c_prior_values = c(0, 1)
)

samples_gcm <- mod_GCM$sample(
  data = gcm_data,
  seed = 123,
  chains = 1,
  parallel_chains = 1,
  threads_per_chain = 4,
  iter_warmup = 1000,
  iter_sampling = 1000,
  refresh = 500
)

```


```{r}
draws_df <- as_draws_df(samples_gcm$draws())

pp1 <- ggplot(draws_df) +
  geom_density(aes(c), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(c_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = d$c[1]) +
  theme_bw()

pp2 <- ggplot(draws_df) +
  geom_density(aes(`w[1]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[1]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 0) +
  theme_bw()

pp3 <- ggplot(draws_df) +
  geom_density(aes(`w[2]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[2]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 0) +
  theme_bw()

pp4 <- ggplot(draws_df) +
  geom_density(aes(`w[3]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[3]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 0) +
  theme_bw()

pp5 <- ggplot(draws_df) +
  geom_density(aes(`w[4]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[4]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 1) +
  theme_bw()

pp6 <- ggplot(draws_df) +
  geom_density(aes(`w[5]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[5]`), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = 0) +
  theme_bw()

(pp1+pp2+pp3)/(pp4+pp5+pp6)
```
```{r}
# fitting weighted bayes to empirical data 
loo_list = c()

for (i in seq(6)){
  df_temp <- df %>% 
    filter(subject == i)
  
  gcm_data <- list(
    ntrials = nrow(df_temp),
    nfeatures = 5,
    cat_one = df_temp$dangerous,
    y = df_temp$response,
    obs = as.matrix(df_temp[, c("col1", "col2", "col3", "col4", "col5")]),
    w_prior_values = c(1, 1, 1, 1, 1),
    c_prior_values = c(0, 1)
  )

  

  samples_gcm <- mod_GCM$sample(
    data = gcm_data,
    seed = 123,
    chains = 1,
    parallel_chains = 1,
    threads_per_chain = 4,
    iter_warmup = 1000,
    iter_sampling = 1000,
    refresh = 500
  )
    
  loo_list = c(loo_list, samples_gcm$loo())
  
  temp <- as_draws_df(samples_gcm$draws())
  temp <- temp %>% 
    mutate(subject = i)
  

  if (exists("draws_df_emp")) { draws_df_emp <- rbind(draws_df_emp, temp)} 
  else{draws_df_emp <- temp} 

}
```
```{r}

draws_df_emp %>% 
  ggplot() +
    geom_density(aes(c), alpha = 0.6, fill = "lightblue")+
    geom_density(aes(c_prior), alpha = 0.6, fill = "pink")+
    facet_wrap(~subject)+
    theme_bw()

draws_df_emp %>% 
  ggplot() +
    geom_density(aes(`w[1]`), alpha = 0.6, fill = "lightblue") +
    geom_density(aes(`w_prior[1]`), alpha = 0.6, fill = "pink") +
    facet_wrap(~subject)+
    theme_bw()

draws_df_emp %>% 
  ggplot() +
    geom_density(aes(`w[2]`), alpha = 0.6, fill = "lightblue") +
    geom_density(aes(`w_prior[2]`), alpha = 0.6, fill = "pink") +
    facet_wrap(~subject)+
    theme_bw()

draws_df_emp %>% 
  ggplot() +
     geom_density(aes(`w[3]`), alpha = 0.6, fill = "lightblue") +
    geom_density(aes(`w_prior[3]`), alpha = 0.6, fill = "pink") +
    facet_wrap(~subject)+
    theme_bw()

draws_df_emp %>% 
  ggplot() +
    geom_density(aes(`w[4]`), alpha = 0.6, fill = "lightblue") +
    geom_density(aes(`w_prior[4]`), alpha = 0.6, fill = "pink") +
    facet_wrap(~subject)+
    theme_bw()
draws_df_emp %>% 
  ggplot() +
    geom_density(aes(`w[5]`), alpha = 0.6, fill = "lightblue") +
    geom_density(aes(`w_prior[5]`), alpha = 0.6, fill = "pink") +
    facet_wrap(~subject)+
    theme_bw()
```
```{r}
p1 <- ggplot(draws_df_emp, aes(.iteration, c, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p2 <- ggplot(draws_df_emp, aes(.iteration, logit_c, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
```

```{r}
p3 <- ggplot(draws_df_emp, aes(.iteration, `w[1]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p4 <- ggplot(draws_df_emp, aes(.iteration, `w[2]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p5 <- ggplot(draws_df_emp, aes(.iteration, `w[3]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p6 <- ggplot(draws_df_emp, aes(.iteration, `w[4]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p7 <- ggplot(draws_df_emp, aes(.iteration, `w[5]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

(p1+p2)/(p3+p4+p5+p6+p7)

```
