---
title: "ass4_mia"
output: html_document
date: "2023-05-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# packages

pacman::p_load(tidyverse, cmdstanr, brms, furrr)

# load data 

df_raw = read.table('AlienData.txt',sep=',', header = T)

df <- df_raw %>% 
  filter(session == 2,
         condition == 2)

```

```{r}
# simulate features

eyes <- c(0,1)
spots <- c(0,1)
color <- c(0,1)
arms <- c(0,1)
legs <- c(0,1)

stimuli <- expand_grid(eyes, spots, color, arms, legs)

stimuli <- stimuli %>% 
  mutate(danger = ifelse(arms == 1, 1, 0),
         stimulus = row_number())

```

```{r}
sequence <- c()
for (i in 1:3) {
  temp <- sample(seq(32), 32, replace = F)
  sequence <- append(sequence, temp)
}

exp <- tibble(stimulus = sequence)

experiment <-  merge(stimuli, exp)

experiment <-  experiment[sample(1:nrow(experiment)), ]

```

```{r}
# Distance 
distance <- function(vect1, vect2, w) {
  return(sum(w * abs(vect1 - vect2)))
}

# Similarity
similarity <- function(distance, c) {
  return(exp(-c * distance))
}
```

```{r}
gcm <- function(w, c, obs, cat_one, quiet = TRUE) {
  # create an empty list to save probability of saying "1" for each trial
  r <- c()
  
  ntrials <- nrow(obs)
  
  for (i in 1:ntrials) {
    # If quiet is FALSE, print every ten trials
    if (!quiet && i %% 10 == 0) {
      print(paste("i =", i))
    }
    # if this is the first trial, or there any category with no exemplars seen yet, set the choice to random
    if (i == 1 || sum(cat_one[1:(i - 1)]) == 0 || sum(cat_one[1:(i - 1)]) == (i - 1)) {
      r <- c(r, .5)
    } else {
      similarities <- c()
      # for each previously seen stimulus assess distance and similarity
      for (e in 1:(i - 1)) {
        sim <- similarity(distance(obs[i, ], obs[e, ], w), c)
        similarities <- c(similarities, sim)
      }
      # Calculate prob of saying "1" by dividing similarity to 1 by the sum of similarity to 1 and to 2
      numerator <- sum(similarities[cat_one[1:(i - 1)] == 1])
      
      denominator <- sum(similarities[cat_one[1:(i - 1)] == 1]) + sum(similarities[cat_one[1:(i - 1)] == 0])
      
      r <- c(r, numerator / denominator)
    }
  }

  return(rbinom(ntrials, 1, r))
}
```


```{r}
# function for simulation responses
simulate_responses <- function(agent, w, c) {
    
    observations <- experiment %>%
        select(-c("stimulus", "danger"))
    
    category <- experiment$danger
    
    if (w == "equal") {
        weight <- rep(1 / 5, 5)
    } 
    # else if (w == "skewed1") {
    #     weight <- c(0, 1)
    # } else if (w == "skewed2") {
    #     weight <- c(0.1, 0.9)
    # }

    # simulate responses
    responses <- gcm(
        weight,
        c,
        observations,
        category
    )
    
    tmp_simulated_responses <- experiment %>%
        mutate(
            trial = seq(nrow(experiment)),
            sim_response = responses,
            correct = ifelse(category == sim_response, 1, 0),
            performance = cumsum(correct) / seq_along(correct),
            c = c,
            w = w,
            agent = agent
        )

    return(tmp_simulated_responses)
}


# simulate responses

param_df <- dplyr::tibble(
    expand_grid(
        agent = 1:10,
        c = seq(1.1),
        w = c("equal")
    )
)

simulated_responses <- future_pmap_dfr(param_df,
    simulate_responses,
    .options = furrr_options(seed = TRUE)
)

```

```{r}
file <- file.path("gcm.stan")
mod_GCM <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
```


```{r}
d = simulated_responses

gcm_data <- list(
  ntrials = nrow(d),
  nfeatures = 5,
  cat_one = d$danger,
  y = d$sim_response,
  obs = as.matrix(d[, c("eyes", "spots", "color", "arms", "legs")]),
  w_prior_values = c(1, 1, 1, 1, 1),
  c_prior_values = c(0, 1)
)

samples_gcm <- mod_GCM$sample(
  data = gcm_data,
  seed = 123,
  chains = 1,
  parallel_chains = 1,
  threads_per_chain = 4,
  iter_warmup = 1000,
  iter_sampling = 1000,
  refresh = 500
)
```

```{r}
samples_gcm$summary()
```

```{r}
draws_df <- as_draws_df(samples_gcm$draws())

ggplot(draws_df, aes(.iteration, c, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_df, aes(.iteration, logit_c, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
```

```{r}
ggplot(draws_df, aes(.iteration, `w[1]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_df, aes(.iteration, `w[2]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_df, aes(.iteration, `w[3]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_df, aes(.iteration, `w[4]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_df, aes(.iteration, `w[5]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

```
```{r}
ggplot(draws_df) +
  geom_density(aes(c), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(c_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = d$c[1]) +
  theme_bw()
```

```{r}
ggplot(draws_df) +
  geom_density(aes(`w[1]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[1]`), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = 0.2) +
  theme_bw()

ggplot(draws_df) +
  geom_density(aes(`w[2]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[2]`), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = 0.2) +
  theme_bw()

ggplot(draws_df) +
  geom_density(aes(`w[3]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[3]`), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = 0.2) +
  theme_bw()

ggplot(draws_df) +
  geom_density(aes(`w[4]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[4]`), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = 0.2) +
  theme_bw()

ggplot(draws_df) +
  geom_density(aes(`w[5]`), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(`w_prior[5]`), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = 0.2) +
  theme_bw()
```

